blank_issues_enabled: false
contact_links:
  - name: 💬 Discord
    url: https://discord.com/invite/teneoprotocol
    about: Join our Discord for help and discussions!
  - name: 📚 Documentation
    url: https://teneo-protocol.ai/data-access
    about: Find setup guides and learn how to use Teneo SDK