/**
 * Error code enum for Teneo Protocol SDK
 * Provides type-safe error codes to prevent typos and enable autocomplete
 */

export enum ErrorCode {
  // SDK errors
  SDK_DESTROYED = "SDK_DESTROYED",
  NOT_CONNECTED = "NOT_CONNECTED",
  INVALID_CONFIG = "INVALID_CONFIG",
  CONFIG_ERROR = "CONFIG_ERROR",

  // Connection errors
  CONNECTION_ERROR = "CONNECTION_ERROR",
  CONNECTION_TIMEOUT = "CONNECTION_TIMEOUT",
  CONNECTION_CLOSED = "CONNECTION_CLOSED",

  // Auth errors
  AUTH_ERROR = "AUTH_ERROR",
  AUTH_TIMEOUT = "AUTH_TIMEOUT",
  AUTH_INVALID_SIGNATURE = "AUTH_INVALID_SIGNATURE",

  // Message errors
  MESSAGE_ERROR = "MESSAGE_ERROR",
  MESSAGE_TIMEOUT = "MESSAGE_TIMEOUT",
  MESSAGE_TOO_LARGE = "MESSAGE_TOO_LARGE",

  // Validation errors
  VALIDATION_ERROR = "VALIDATION_ERROR",
  INVALID_MESSAGE = "INVALID_MESSAGE",
  SIGNATURE_VERIFICATION_ERROR = "SIGNATURE_VERIFICATION_ERROR",

  // Webhook errors
  WEBHOOK_ERROR = "WEBHOOK_ERROR",
  WEBHOOK_TIMEOUT = "WEBHOOK_TIMEOUT",
  WEBHOOK_INVALID_URL = "WEBHOOK_INVALID_URL",

  // Rate limit
  RATE_LIMIT = "RATE_LIMIT",

  // Generic timeout (for backward compatibility)
  TIMEOUT_ERROR = "TIMEOUT_ERROR",
  TIMEOUT = "TIMEOUT"
}
