/**
 * Error code enum for Teneo Protocol SDK
 * Provides type-safe error codes to prevent typos and enable autocomplete
 */

export enum ErrorCode {
  // SDK errors
  SDK_DESTROYED = "SDK_DESTROYED",
  NOT_CONNECTED = "NOT_CONNECTED",
  INVALID_CONFIG = "INVALID_CONFIG",
  CONFIG_ERROR = "CONFIG_ERROR",

  // Connection errors
  CONNECTION_ERROR = "CONNECTION_ERROR",
  CONNECTION_TIMEOUT = "CONNECTION_TIMEOUT",
  CONNECTION_CLOSED = "CONNECTION_CLOSED",

  // Auth errors
  AUTH_ERROR = "AUTH_ERROR",
  AUTH_TIMEOUT = "AUTH_TIMEOUT",
  AUTH_INVALID_SIGNATURE = "AUTH_INVALID_SIGNATURE",

  // Message errors
  MESSAGE_ERROR = "MESSAGE_ERROR",
  MESSAGE_TIMEOUT = "MESSAGE_TIMEOUT",
  MESSAGE_TOO_LARGE = "MESSAGE_TOO_LARGE",

  // Validation errors
  VALIDATION_ERROR = "VALIDATION_ERROR",
  INVALID_MESSAGE = "INVALID_MESSAGE",
  SIGNATURE_VERIFICATION_ERROR = "SIGNATURE_VERIFICATION_ERROR",

  // Webhook errors
  WEBHOOK_ERROR = "WEBHOOK_ERROR",
  WEBHOOK_TIMEOUT = "WEBHOOK_TIMEOUT",
  WEBHOOK_INVALID_URL = "WEBHOOK_INVALID_URL",

  // Rate limit
  RATE_LIMIT = "RATE_LIMIT",

  // Room Management errors (v2.0.0)
  OPERATION_FAILED = "OPERATION_FAILED",
  PERMISSION_DENIED = "PERMISSION_DENIED",

  // Quote-Approve Payment errors (v2.2.0)
  QUOTE_EXPIRED = "QUOTE_EXPIRED",
  QUOTE_NOT_FOUND = "QUOTE_NOT_FOUND",
  QUOTE_TIMEOUT = "QUOTE_TIMEOUT",
  PRICE_LIMIT_EXCEEDED = "PRICE_LIMIT_EXCEEDED",
  INVALID_PAYMENT_NETWORK = "INVALID_PAYMENT_NETWORK",
  INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  PAYMENT_SIGNATURE_FAILED = "PAYMENT_SIGNATURE_FAILED",

  // Auto-summon errors (v2.4.0)
  AGENT_NOT_IN_ROOM = "AGENT_NOT_IN_ROOM",
  AGENT_NOT_FOUND = "AGENT_NOT_FOUND",
  AUTOSUMMON_FAILED = "AUTOSUMMON_FAILED",

  // Generic timeout (for backward compatibility)
  TIMEOUT_ERROR = "TIMEOUT_ERROR",
  TIMEOUT = "TIMEOUT"
}
