
name: Mirror Release Branch to TeneoProtocolAI Repo
on:
  push:
    branches:
      - main

jobs:
  mirror-to-test-repo:
    if: github.repository == 'Teneo-Protocol/teneo-sdk'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror main → main
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: git@github.com:TeneoProtocolAI/teneo-sdk.git
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          PUSH_ALL_REFS: "false"
          GIT_PUSH_ARGS: "--tags --force --prune"
          GIT_SSH_NO_VERIFY_HOST: "true"
